[tools]
"cargo:jj-cli" = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "latest"
"npm:@openai/codex" = "latest"
"npm:bash-language-server" = "latest"
rust = "latest"
"npm:hunkdiff" = "latest"
lazygit = "latest"

[settings]
experimental = true
minimum_release_age = "0s"
