#!/bin/bash

MODE=$1

if [ "$MODE" == "all" ]; then
  # DEEP SCAN:
  # -maxdepth 3 allows for ~/dev/org/repo
  # We exclude hidden folders (path '*/.*') to keep it clean
  find ~/ -maxdepth 3 -mindepth 1 -type d 2>/dev/null
else
  # FAST SCAN (Default):
  # Only return what Zoxide knows
  if command -v zoxide &>/dev/null; then
    zoxide query -l
  fi
fi
